### ISSUE TITLE
예약 서비스의 예약 시간 테이블을 구현한다.

### ISSUE THREAD

**Issue by hyunw9** [ShallWeProject/ShallWeProject_Server#136]
## 🤷 구현할 기능
기존 예약 방식은 
id | created_at | status | updated_at | date | invitation_comment | invitation_img | persons | phone_number | reservation_status | experience_gift_id (fk) | receiver_id (fk) | sender_id (fk) | receiver | user_id | sender 

로 구성된 테이블을 이용했습니다. 
현재 테이블은 사용하지 않는 컬럼도 다수 존재하고, 컬럼이 너무 많아 변동에 취약한 것 같습니다. 
예약 기능을 구현하기 위해서는 예약 시간을 담아두는 테이블이 따로 필요할 것이라 생각됩니다. 

<available_date> 
|id|판매자_id|날짜|
|---|---|---|
|1|1|2023-10-08|
|2|1|2023-10-19|

<available_time>
|판매자_id|날짜(참조)|시간|
|---|---|---|
|1|1|19:00|
|1|2|20:00|

이런 식으로 구상해봤습니다. 
혹시 다른 의견 있으시면 comment 달아주시면 감사하겠습니다 ! 

## 🔨 상세 작업 내용

- [x] 사용하지 않는 column 제거
- [ ] 날짜 테이블 생성
- [ ] 서비스 코드 변경

## ⏰ 3시간

**Comment by sejineer** [comment]
너무 좋은 아이디어네요!!

**Comment by leeseunghakhello** [comment]
동의합니다!
