### ISSUE TITLE
예약 관련 수정사항을 적용한다.

### ISSUE THREAD

**Issue by hyunw9** [ShallWeProject/ShallWeProject_Server#285]
## 🤷 구현할 기능
예약 관련 수정사항을 적용
## 🔨 상세 작업 내용

- [x] 예약 수정시 상태 변경
- [ ] 유저 예약 추가 요청 보낼 때, 예약 Id 만 전송하도록 변경
- [x] 예약 추가 관련 동시성 처리 

## ⏰ 예상 소요 기간

**Comment by sejineer** [comment]
변경 후 변경된 점 서버 패치노트 작성도 부탁드립니닷
